### ISSUE TITLE
无法找到 CITE_PBMC_AE_weights.pth.tar

### ISSUE THREAD

**Issue by cucumber2249** [ttgump/scDCC#1]
请问这个模型可以在哪找到

**Comment by ttgump** [comment]
Hi, I have uploaded the pre-trained weights. Thanks.
Best,
Tian

**Comment by ttgump** [comment]
> 请问这个模型可以在哪找到

Hi, I have uploaded the pre-trained weights. Thanks.
Best,
Tian
